package net.fayber.faybergui.widget;

import com.mojang.blaze3d.platform.NativeImage;
import com.mojang.blaze3d.systems.RenderSystem;
import com.mojang.blaze3d.textures.FilterMode;
import net.fayber.faybergui.FayberGuiClient;
import net.fayber.faybergui.render.Ui;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.renderer.RenderPipelines;
import net.minecraft.client.renderer.texture.DynamicTexture;
import net.minecraft.resources.Identifier;
import net.minecraft.server.packs.resources.Resource;
import org.slf4j.Logger;

import java.io.InputStream;

/**
 * The library's UI glyphs, as sprites from a pre-rendered atlas ({@code textures/gui/icons.png},
 * generated by {@code tools/gen-icons.java} from the Lucide icon set, ISC license, see NOTICE).
 *
 * <p>Drawing glyphs from {@link Ui} primitives each frame aliases badly: strokes are
 * re-rasterised at whatever odd size a button happens to be, so curves come out lumpy and round
 * joints develop slivers. The atlas instead holds each icon rasterised once at high resolution
 * with real anti-aliasing, and drawing it is a bilinear-filtered tinted quad, which stays smooth
 * at every GUI scale and every widget size, the way a UI toolkit does it.
 *
 * <p>Mods that need their own glyphs can implement {@link Glyph} directly (any drawer works) or
 * copy {@code tools/gen-icons.java} to produce an atlas in their own namespace; the icon-drawing
 * entry point is a simple functional interface on purpose.
 *
 * <p>The atlas texture registers itself with a {@code LINEAR} sampler: {@link DynamicTexture}
 * hard-codes the blocky {@code NEAREST} one, and in this rendering stack filtering is a property
 * of the sampler, not the texture, so the subclass below swaps it after construction.
 */
public final class Icons {
    /** Atlas cell, 3x the 24-unit Lucide grid; must match tools/gen-icons.java. */
    private static final int CELL = 72;
    private static final int COLS = 4;
    private static final int ATLAS_W = CELL * COLS;
    /** 17 icons in 4 columns: five rows. Must match tools/gen-icons.java. */
    private static final int ATLAS_H = CELL * 5;
    /** Where the PNG lives in resources. */
    private static final Identifier ATLAS_ASSET =
            Identifier.fromNamespaceAndPath(FayberGuiClient.MOD_ID, "textures/gui/icons.png");
    /** The registered texture name used when blitting. */
    private static final Identifier ATLAS_TEXTURE =
            Identifier.fromNamespaceAndPath(FayberGuiClient.MOD_ID, "gui/icons");

    /** An icon: drawn centred on ({@code cx}, {@code cy}) inside a {@code size} x {@code size} box. */
    @FunctionalInterface
    public interface Glyph {
        void draw(GuiGraphicsExtractor gfx, float cx, float cy, float size, int color);
    }

    /** Chevron down (dropdowns, collapsible sections). */
    public static final Glyph CHEVRON_DOWN = glyph(0);
    /** Chevron up (collapsible sections, steppers). */
    public static final Glyph CHEVRON_UP = glyph(1);
    /** Chevron left (pagination, back buttons). */
    public static final Glyph CHEVRON_LEFT = glyph(2);
    /** Chevron right (pagination, forward). */
    public static final Glyph CHEVRON_RIGHT = glyph(3);
    /** Checkmark (checkboxes, confirmations, success toasts). */
    public static final Glyph CHECK = glyph(4);
    /** Cross (close and dismiss actions). */
    public static final Glyph X = glyph(5);
    /** Plus sign (add actions, steppers). */
    public static final Glyph PLUS = glyph(6);
    /** Minus sign (steppers). */
    public static final Glyph MINUS = glyph(7);
    /** Magnifier (search fields). */
    public static final Glyph SEARCH = glyph(8);
    /** Gear (settings actions). */
    public static final Glyph GEAR = glyph(9);
    /** Keyboard (keybind capture). */
    public static final Glyph KEYBOARD = glyph(10);
    /** Info circle (informational toasts). */
    public static final Glyph INFO = glyph(11);
    /** Warning triangle (warning toasts and dialogs). */
    public static final Glyph ALERT = glyph(12);
    /** Check inside a circle (success toasts). */
    public static final Glyph CHECK_CIRCLE = glyph(13);
    /** X inside a circle (error toasts). */
    public static final Glyph X_CIRCLE = glyph(14);
    /** Solid dot, useful as a generic colour swatch. */
    public static final Glyph DOT = glyph(15);
    /** Counter-clockwise rotation arrow (reset to default actions). */
    public static final Glyph ROTATE_CCW = glyph(16);

    private static boolean registered;
    private static final Logger LOGGER = FayberGuiClient.LOGGER;

    private Icons() {
    }

    private static Glyph glyph(int index) {
        return (gfx, cx, cy, size, color) -> draw(gfx, index, cx, cy, size, color);
    }

    private static void draw(GuiGraphicsExtractor gfx, int index, float cx, float cy, float size, int color) {
        ensureRegistered();
        float s = Ui.scale();
        int px = Math.max(1, Math.round(size * s));
        int x0 = Math.round(cx * s) - px / 2;
        int y0 = Math.round(cy * s) - px / 2;
        int u = (index % COLS) * CELL;
        int v = (index / COLS) * CELL;
        gfx.pose().pushMatrix();
        gfx.pose().scale(1.0f / s, 1.0f / s);
        // The long blit overload separates destination size from source texels: the full CELLxCELL
        // cell is sampled into a px-px quad. (The short overload samples w x h texels, which would
        // magnify one corner of the cell.)
        gfx.blit(RenderPipelines.GUI_TEXTURED, ATLAS_TEXTURE, x0, y0, u, v,
                px, px, CELL, CELL, ATLAS_W, ATLAS_H, color);
        gfx.pose().popMatrix();
    }

    /** Loads and registers the atlas the first time an icon is drawn (always on the render thread). */
    private static void ensureRegistered() {
        if (registered) {
            return;
        }
        registered = true;
        try {
            Resource resource = Minecraft.getInstance().getResourceManager().getResource(ATLAS_ASSET)
                    .orElseThrow(() -> new IllegalStateException("missing " + ATLAS_ASSET));
            NativeImage image;
            try (InputStream in = resource.open()) {
                image = NativeImage.read(in);
            }
            Minecraft.getInstance().getTextureManager().register(ATLAS_TEXTURE, new LinearTexture(image));
        } catch (Exception e) {
            LOGGER.error("Failed to load the icon atlas", e);
        }
    }

    /** {@link DynamicTexture} always installs a NEAREST sampler; icons need bilinear. */
    private static final class LinearTexture extends DynamicTexture {
        private LinearTexture(NativeImage image) {
            super(() -> FayberGuiClient.MOD_ID + "/icons", image);
            this.sampler = RenderSystem.getSamplerCache().getRepeat(FilterMode.LINEAR);
        }
    }
}
